export const ADMIN_ROUTE = '/admin'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const DEVISE_ROUTE = '/device'
export const LOGIN_ROUTE = '/login'